
export const PATIENT_LOGIN= "PATIENT_LOGIN";
export const PATIENT_LOGIN_WATCHER= "PATIENT_LOGIN_WATCHER";

export const PATIENT_LOGOUT ="PATIENT_LOGOUT";
export const PATIENT_LOGOUT_WATCHER = "PATIENT_LOGOUT_WATCHER";

export const PATIENT_PASSWORD_RESET_REQ = "PATIENT_PASSWORD_RESET_REQ";
export const PATIENT_PASSWORD_RESET_REQ_WATCHER = "PATIENT_PASSWORD_RESET_REQ_WATCHER";

export const PATIENT_PASSWORD_RESET_WATCHER = "PATIENT_PASSWORD_RESET_WATCHER";
export const PATIENT_PASSWORD_RESET = "PATIENT_PASSWORD_RESET";

export const PATIENT_GET_ALL_PRACTICE_WATCHER = "PATIENT_GET_ALL_PRACTICE_WATCHER";
export const PATIENT_GET_ALL_PRACTICE = "PATIENT_GET_ALL_PRACTICE"



export const API_FAILED = "API_FAILED";
export const API_ERROR_RESET = "API_ERROR_RESET"

export const IS_LOADING = "IS_LOADING";
export const LOADED = "LOADED";
export const LOAD_FAILED = "LOAD_FAILED";
